version: "3"
volumes:
  postgresql-data: {}

services:
  rabbitmq:
    image: rabbitmq:3.9.5
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:14.7
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - ENV POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecurepassword
      - POSTGRES_DB=ayuktdb

  django-app:
    image: django-app
    build:
      context: .
      dockerfile: ./Dockerfile.app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    tty: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

    command: sh -c "while ! nc -z rabbitmq 5672; do sleep 1; done && python3 manage.py runserver"
