version: '2'

volumes:
  postgres_data: {}
  postgres_data_backups: {}
  production_caddy: {}


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: urban_piper_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - "80:80"
      - "8000:8000"


  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: urban_piper_production_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - default


  redis:
    image: redis:3.2
